# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3329580ff8bf33f1ad74b9d6b146bca03ea229be772b426310bc2b93969bebdbc3afb8f76fdc21cb22bfa8a25a9f4047fac25e4d35f2c546fbe2f708bc36e6

test:
  secret_key_base: e2d2a8b94be9e467fd25efd613ce03d6ec7532978cede6fb3387400852359c780b78c43dd61e74202d563dd7da50443610bb9ee4f2aee7895f904eae10d74642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
